import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st
from babel.numbers import format_currency
sns.set(style='dark')
# set title web
st.set_page_config(page_title='Dashboard Bike Sharing', page_icon='🚲', layout='wide', initial_sidebar_state='auto')
def create_daily_users(df):
  daily_users_df = df.resample(rule='D', on='dateday').agg({ 
    'registered': 'sum',
    'casual': 'sum',
    'total': 'sum'
  })
  daily_users_df= daily_users_df.reset_index()
  return daily_users_df

def create_type_users(df):
  type_users_df = df[['casual', 'registered']].sum()
  return type_users_df

def create_workingday_users(df):
  workingday_users_df = df.groupby('workingday').agg({
    'casual': 'sum',
    'registered': 'sum',
    'total': 'sum'
  }).sort_values(by='total', ascending=True)
  return workingday_users_df

def create_weather_users(df):
  weather_users_df = df.groupby('weather_situation').agg({
    'casual': 'sum',
    'registered': 'sum',
    'total': 'sum'
  }).sort_values(by='total', ascending=False)
  return weather_users_df

def create_season_users(df):
  season_users_df = df.groupby('season').agg({
    'casual': 'sum',
    'registered': 'sum',
    'total': 'sum'
  }).sort_values(by='total', ascending=False)
  return season_users_df

def create_hour_users(df):
  hour_users_df = df.groupby('hour').agg({
    'casual': 'sum',
    'registered': 'sum',
    'total': 'sum'
  }).sort_values(by='total', ascending=False)
  return hour_users_df

all_df = pd.read_csv('main_data.csv')

all_df.sort_values(by='dateday', inplace=True)
all_df.reset_index(inplace=True)

all_df['dateday'] = pd.to_datetime(all_df['dateday'])

min_date = all_df['dateday'].min()
max_date = all_df['dateday'].max()


with st.sidebar:
    st.title('Dashboard')

    st.image("https://scontent.fbdo3-1.fna.fbcdn.net/v/t39.30808-6/302350418_585681089826929_7189388207338572555_n.jpg?_nc_cat=103&ccb=1-7&_nc_sid=efb6e6&_nc_ohc=axmqul8-KjIAX8tmkzn&_nc_zt=23&_nc_ht=scontent.fbdo3-1.fna&oh=00_AfC1vpK0qwuECeS0eYCzTjzos82D9t6YoES7h4TwEZBjBw&oe=65B70139")
    
    start_date, end_date = st.date_input(
        label='Rentang Waktu',
        min_value=min_date,
        max_value=max_date,
        value=[min_date, max_date],
        format='DD-MM-YYYY'
    )

main_df = all_df[(all_df["dateday"] >= str(start_date)) & (all_df["dateday"] <= str(end_date))]

daily_users_df = create_daily_users(main_df)
type_users_df = create_type_users(main_df)
workingday_users_df = create_workingday_users(main_df)
weather_users_df = create_weather_users(main_df)
season_users_df = create_season_users(main_df)
hour_users_df = create_hour_users(main_df)

st.title('Analisis Data Bike Sharing')

tabs1, tabs2, tabs3,tabs4,tabs5,tabs6,tabs7 = st.tabs(['Background','Question1','Question2','Question3','Question4','Question5','Question6'])

with tabs1:
  st.header('Background')
  st.subheader('Bike Sharing')
  st.write('''
    Bike sharing systems are new generation of traditional bike rentals where whole process from membership, rental and return 
    back has become automatic. Through these systems, user is able to easily rent a bike from a particular position and return 
    back at another position. Currently, there are about over 500 bike-sharing programs around the world which is composed of 
    over 500 thousands bicycles. Today, there exists great interest in these systems due to their important role in traffic, 
    environmental and health issues. 

    Apart from interesting real world applications of bike sharing systems, the characteristics of data being generated by
    these systems make them attractive for the research. Opposed to other transport services such as bus or subway, the duration
    of travel, departure and arrival position is explicitly recorded in these systems. This feature turns bike sharing system into
    a virtual sensor network that can be used for sensing mobility in the city. Hence, it is expected that most of important
    events in the city could be detected via monitoring these data.
  ''')

  st.subheader('Dataset')
  st.write('''
    Bike-sharing rental process is highly correlated to the environmental and seasonal settings. For instance, weather conditions,
    precipitation, day of week, season, hour of the day, etc. can affect the rental behaviors. The core data set is related to  
    the two-year historical log corresponding to years 2011 and 2012 from Capital Bikeshare system, Washington D.C., USA which is 
    publicly available in http://capitalbikeshare.com/system-data. We aggregated the data on two hourly and daily basis and then 
    extracted and added the corresponding weather and seasonal information. Weather information are extracted from http://www.freemeteo.com. 
  ''')


with tabs2:
  st.subheader('Daily Users')

  col1, col2, col3 = st.columns(3)

  with col1:
    registered = format_currency(daily_users_df['registered'].sum(), '', locale='id_ID', format='##,###.##')
    st.metric('Registered Users',value=registered)
  with col2:
    casual = format_currency(daily_users_df['casual'].sum(), '', locale='id_ID', format='##,###.##')
    st.metric('Casual Users',value=casual)
  with col3:
    total = format_currency(daily_users_df['total'].sum(), '', locale='id_ID', format='##,###.##')
    st.metric('Total Users',value=total)

  st.header('Bagaimana perkembangan pengguna bike sharing dari tahun 2011-2012?')
  
  st.subheader('Answer :')
  st.write('''
      Terdapat peningkatan > 50% total pengguna bike sharing di tahun 2012 dibanding 2011
  ''')
  fig, ax = plt.subplots(figsize=(20, 10))
  ax.plot(daily_users_df['dateday'], daily_users_df['casual'], label='Casual', marker='o')
  ax.plot(daily_users_df['dateday'], daily_users_df['registered'], label='Registered', marker='o')
  ax.plot(daily_users_df['dateday'], daily_users_df['total'], label='Total', marker='o')
  ax.set_title('Daily Users', fontsize=24)
  ax.legend(fontsize=20)
  ax.grid(axis='y', linestyle='-', alpha=0.5, zorder=0, color='gray')
  ax.set_xlabel('Date', fontsize=20)
  ax.set_ylabel('Users', fontsize=20)
  ax.tick_params(axis='y', labelsize=20)
  ax.tick_params(axis='x', labelsize=15)
  st.pyplot(fig)

with tabs3:
  st.header('Bagaimana perbandingan antara pengguna casual dan registered dari total pengguna bike sharing?')
  
  st.subheader('Answer :')
  st.write('''
      Perbandingan jenis pengguna bike sharing dari 2011 - 2012 adalah 81.2% pengguna registered dan 18.2% pengguna casual.
  ''')

  fig,ax = plt.subplots(figsize=(10, 10))
  plt.pie(
    type_users_df,
    labels=('Casual', 'Registered'),
    colors=['#FF6F61', '#66B2FF'],
    autopct='%1.1f%%',
    textprops={'fontsize': 14, 'color': 'black'},
    startangle=90,
    shadow=True,
  )
  plt.axis('equal')
  plt.title('Persentasi jenis Pengguna Bike Sharing dari ', fontsize=20)
  st.pyplot(fig)

with tabs4:
  st.header('Bagaimana perbandingan penggunaan bike sharing pada hari libur dan hari kerja?')
  
  st.subheader('Answer :')
  st.write('''
      Pengguna bike sharing lebih banyak pada hari kerja dibandingkan hari libur
  ''')
  fig, ax = plt.subplots(figsize=(12, 10))
  ax.yaxis.set_major_formatter('{x:,.0f}')
  sns.set_style('whitegrid')
  sns.barplot(x=workingday_users_df.index, y=workingday_users_df['total'], palette='Set2')
  plt.title("Perbandingan Penggunaan Bike Sharing Pada Hari Kerja dan Bukan Hari Kerja")
  plt.xlabel(None)
  plt.ylabel('Users')
  st.pyplot(fig)

with tabs5:
  st.header('Bagaimana perbandingan penggunaan bike sharing berdasarkan keadaan cuaca?')
  
  st.subheader('Answer :')
  st.write('''
      Penggunaan bike sharing terbanyak terkait kondisi cuaca adalah pada cuaca cerah, diikuti oleh kabut + awan, hujan ringan/salju, dan hujan lebat/angin kencang dengan penggunaan terendah.
  ''')
  fig,ax = plt.subplots(figsize=(12, 10))

  ax.yaxis.set_major_formatter('{x:,.0f}')
  sns.set_style('whitegrid')
  sns.barplot(x=weather_users_df.index, y=weather_users_df['total'], palette='Set2')
  plt.title("Perbandingan Penggunaan Bike Sharing Berdasarkan Keadaan Cuaca")
  plt.xlabel(None)
  plt.ylabel('Users')
  st.pyplot(fig)

with tabs6:
  st.header('Bagaimana perbandingan penggunaan bike sharing berdasarkan keadaan musim?')
  
  st.subheader('Answer :')
  st.write('''
      Bike sharing paling banyak digunakan pada musim fall, diikuti oleh summer, winter, dan springer dengan jumlah pengguna terendah.
  ''')
  fig,ax = plt.subplots(figsize=(12, 10))
  ax.yaxis.set_major_formatter('{x:,.0f}')
  sns.set_style('whitegrid')
  sns.barplot(x=season_users_df.index, y=season_users_df['total'], palette='Set2')
  plt.title("Perbandingan Penggunaan Bike Sharing Berdasarkan Keadaan Musim")
  plt.xlabel(None)
  plt.ylabel('Users')
  st.pyplot(fig)

with tabs7:
  st.header('Pada pukul berapa penggunaan bike sharing terbanyak dan terendah?')
  
  st.subheader('Answer :')
  st.write('''
      Jam puncak penggunaan bike sharing terjadi pada pukul 5 PM dan paling rendah pada pukul 4 AM.
  ''')
  fig,ax = plt.subplots(figsize=(12, 10))
  ax.xaxis.set_major_formatter('{x:,.0f}')
  sns.despine(fig)
  sns.set_style('whitegrid')
  sns.barplot(x=hour_users_df['total'], y=hour_users_df.index, palette='Set2', order=hour_users_df.index, orient='h')
  plt.title("Perbandingan Penggunaan Bike Sharing Berdasarkan Jam")
  plt.xlabel(None)
  plt.ylabel('Users')
  st.pyplot(fig)

st.caption('sofyanegi, &copy; 2024')